/*
 * 
 * 
 * 
 */
package mediafileparsers;

import parsers.mp3.Mp3Parser;
import parsers.flac.FlacParser;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Ville
 */
public class TestWindow extends javax.swing.JFrame {

    /**
     * Creates new form TestWindow
     */
    public TestWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbFlacFile = new javax.swing.JTextField();
        bParseFlac = new javax.swing.JButton();
        bBrowseFlac = new javax.swing.JButton();
        tbMp3File = new javax.swing.JTextField();
        bParseMp3 = new javax.swing.JButton();
        bBrowseMp3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMp3Metadata = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFlacMetadata = new javax.swing.JTextArea();
        tbMediaFile = new javax.swing.JTextField();
        bParseMedia = new javax.swing.JButton();
        bBrowse = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMediaMetadata = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbFlacFile.setText("E:\\Musiikki\\Billy Talent\\Billy Talent II\\03 This Suffering.flac");

        bParseFlac.setText("Parse");
        bParseFlac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParseFlacActionPerformed(evt);
            }
        });

        bBrowseFlac.setText("Browse");
        bBrowseFlac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseFlacActionPerformed(evt);
            }
        });

        tbMp3File.setText("E:\\Musiikki\\Billy Talent\\Dead Silence\\02 - Viking Death March.mp3");

        bParseMp3.setText("Parse");
        bParseMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParseMp3ActionPerformed(evt);
            }
        });

        bBrowseMp3.setText("Browse");
        bBrowseMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseMp3ActionPerformed(evt);
            }
        });

        tbMp3Metadata.setColumns(20);
        tbMp3Metadata.setRows(5);
        jScrollPane1.setViewportView(tbMp3Metadata);

        tbFlacMetadata.setColumns(20);
        tbFlacMetadata.setRows(5);
        jScrollPane2.setViewportView(tbFlacMetadata);

        tbMediaFile.setText("E:\\Musiikki\\Billy Talent\\Dead Silence\\02 - Viking Death March.mp3");

        bParseMedia.setText("Parse");
        bParseMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParseMediaActionPerformed(evt);
            }
        });

        bBrowse.setText("Browse");
        bBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseActionPerformed(evt);
            }
        });

        tbMediaMetadata.setColumns(20);
        tbMediaMetadata.setRows(5);
        jScrollPane3.setViewportView(tbMediaMetadata);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBrowseFlac)
                            .addComponent(tbFlacFile, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addComponent(bParseFlac)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBrowseMp3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbMp3File, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bParseMp3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBrowse)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbMediaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bParseMedia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbMediaFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bParseMedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bBrowseFlac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbFlacFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bParseFlac)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bBrowseMp3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbMp3File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bParseMp3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBrowseFlacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowseFlacActionPerformed
        JFileChooser fChooser = new JFileChooser("E:\\Musiikki\\Billy Talent\\Billy Talent II\\03 This Suffering.flac");
        if (fChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            tbFlacFile.setText(fChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_bBrowseFlacActionPerformed

    private void bBrowseMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowseMp3ActionPerformed
        JFileChooser fChooser = new JFileChooser("E:\\Musiikki\\Billy Talent\\Dead Silence\\02 - Viking Death March.mp3");
        if (fChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            tbMp3File.setText(fChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_bBrowseMp3ActionPerformed

    private void bParseFlacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParseFlacActionPerformed
        if (tbFlacFile.getText().isEmpty()) {
            
        } else {
            File f = new File(tbFlacFile.getText());
            FlacParser fParse = new FlacParser(null, f);
            String lyrics = fParse.getLyricsFromFile();
            tbFlacMetadata.setText(lyrics);
        }
    }//GEN-LAST:event_bParseFlacActionPerformed

    private void bParseMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParseMp3ActionPerformed
        // TODO add your handling code here:
        if (tbMp3File.getText().isEmpty()) {
            
        } else {
            File f = new File(tbMp3File.getText());
            Mp3Parser mParse = new Mp3Parser(null, f);
            tbMp3Metadata.setText(mParse.getUnSyncedLyrics());
            mParse.close();
        }
    }//GEN-LAST:event_bParseMp3ActionPerformed

    private void bParseMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParseMediaActionPerformed
        if (tbMediaFile.getText().isEmpty()) {
            
        } else {
            File f = new File(tbMediaFile.getText());
            tbMediaMetadata.setText(ParseController.getLyricsFromFile(null, f));
        }
        
    }//GEN-LAST:event_bParseMediaActionPerformed

    private void bBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowseActionPerformed
        JFileChooser fChooser = new JFileChooser("E:\\Musiikki\\Billy Talent\\Dead Silence\\02 - Viking Death March.mp3");
        if (fChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            tbMediaFile.setText(fChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_bBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBrowse;
    private javax.swing.JButton bBrowseFlac;
    private javax.swing.JButton bBrowseMp3;
    private javax.swing.JButton bParseFlac;
    private javax.swing.JButton bParseMedia;
    private javax.swing.JButton bParseMp3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField tbFlacFile;
    private javax.swing.JTextArea tbFlacMetadata;
    private javax.swing.JTextField tbMediaFile;
    private javax.swing.JTextArea tbMediaMetadata;
    private javax.swing.JTextField tbMp3File;
    private javax.swing.JTextArea tbMp3Metadata;
    // End of variables declaration//GEN-END:variables
}
